export EDITOR='idle'
export VISUAL='idle'
alias l='ls --color=auto -lrt -a'
alias s='source ~/.bash_aliases'
alias gc='gedit ~/.bash_aliases &'
alias get='wget -r 10.50.23.57:8888'
alias log='git log --pretty=oneline'
alias d='cd ~/Desktop'
alias p='cd ~/Desktop/gitrepo/pypeople'
alias v='source pyfamily_venv/bin/activate'
alias dv='deactivate'
alias vimnew='vim ~/.vimrc'
alias venv='python# -m venv venv_name'
alias shebang='./#!/usr/bin/env___python3'
alias ignore='idle ~/.gitignore_global &'
alias github='cd ~/Desktop/github'
alias gitrepo='cd ~/Desktop/gitrepo'
alias ghidra='~/Desktop/puzzles/ghidra_10.2.2_PUBLIC/ghidraRun'
alias hub='cd ~/Desktop/github/'
alias lab='cd ~/Desktop/gitrepo/'
alias myscript='python3.10 ~/Desktop/github/spice_libraries/python/make.py'